### ISSUE TITLE
UX/UI - Star behaviour + swiping

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#87]
Currently users can tap a faded star icon in order to ... do something. 
Tapping the icon does not seem to do anything
Tapping the icon more than once returns an error 'duplicate record exists'
It is difficult to tap the star icon without tapping the event image which takes you to the Event details page
There is no way to see events that you have starred (what is the point of this feature?)
**Proposed Enhancements:**
surface a way to view starred event
swap faded star icon for a 'swipe left to star' behaviour. This will reinforce the concept of swipe actions and navigation throughout the application (see ticket #775) This also solves contrast issues with the faded star icon not being visible on certain background images. 
this would require a few UI updates to make sure that swipe actions on an Event listing is intuitive. Mainly, separating event listings with a light border would emphasise each listing as its own row and would set a comfortable boundary around the information that is swipable.

**Comment by mileTadic1994** [comment]
@Tas4tari 
This feature works. 
The problems are:
1. By clicking on star, event is flagged as interested for user. But it also takes user to page with details for that event. This could be easily fixed by preventing parent event to trigger.
2. User won't see that event is flagged as interested till the API is called again (for example when page is reloaded). This problem could be solved on different ways. One would be to call API again when user hit star. This can be really frustrating for user, cause he shall wait for page to load only because he starred one event.
Other solution would be to use Reacts state to manage these stars. In that way we would use reacts state to make a copy of starred events, and we would handle stars through state. That way user will see that he starred some event and in the background we will call API for marking event as interested/notInterested.

**Comment by Tas4tari** [comment]
@Krakaw could you please advise on the best way forward

**Comment by Krakaw** [comment]
@mileTadic1994 I think the best way forward is set the state of the event to `Starred` locally, that way when you display the event you do not need to re-request the entire event. Only if the `POST` request to mark the event as liked / disliked comes back as a failure would you then need to do any more processing.
